### ISSUE TITLE
Problems with IntelliJ

### ISSUE THREAD

**Issue by bwbecker** [jducoeur/jsext#12]
I've been having trouble with JSOptionsBuilder when using IntelliJ.  The issues are that when using a library that uses JSOptionsBuilder (eg jstree-facade at https://github.com/jducoeur/jstree-facade) IntelliJ does not autocomplete and seems (ie I haven't instrumented it) to use substantially more CPU cycles.

I believe the culprit is the `copy` parameter in `abstract class JSOptionBuilder[T <: js.Object, B <: JSOptionBuilder[T, _]](copy:OptMap => B)...` that somehow messes up IntelliJ.

I have a fork at https://github.com/bwbecker/jsFacadeOptionBuilder that fixes this problem.  It's a breaking change, however, and so I assumed you would not be interested in a pull request.  If you ARE, then please let me know.  I'd re-do it to make fewer changes to your library.

**Comment by jducoeur** [comment]
Huh.  First I've heard of it, and I confess I'm surprised: we're not doing anything terribly complicated.  Not sure why IntelliJ is getting confused.  (But I use Scala-IDE, so I don't have the firsthand experience there.)

At this late date, you're right that I'm going to avoid accepting breaking changes; frankly, I suspect the world is moving towards ScalaJSDefined, now that that's working better.  But I'm glad you were able to come up with a solution that works for you...
